### ISSUE TITLE
ipv6 update causes error

### ISSUE THREAD

**Issue by geotre** [h3rald/nimhttpd#15]
I frequently use nimhttpd to serve static files from containers (thank you for creating it!). After the recent update [Revise app to be dual-stack IPv4+IPv6](https://github.com/h3rald/nimhttpd/commit/7e0342582a912e00bddc03aaaa796b106c5caaeb) I now get this error when running the plain `nimhttpd` command:

```
oserr.nim(95)            raiseOSError
asyncfutures.nim(437)    asyncCheckCallback
Error: unhandled exception: Cannot assign requested address [OSError]
```

Installing the version prior to this commit using `nimble install nimhttpd@#ee386274a8c0491285ac4931fb36175267c42580` works as expected.

**Comment by moigagoo** [comment]
I'm getting the same error but with different wording:
```
oserr.nim(95)            raiseOSError
asyncfutures.nim(437)    asyncCheckCallback
Error: unhandled exception: Address already in use [OSError]
```

**Comment by h3rald** [comment]
I can reproduce this. The problem goes away if you specify an address explicitly... I think by default we are trying to set both the IPv4 and IPv6 addresses to "localhost"... in [e3dcf87](https://github.com/h3rald/nimhttpd/commit/e3dcf87756c521180656c548d935a49f7c75623f) I changed this to use the actual loopback addresses as default, and everything works as expected.

I will release this soon, but please try this out if you can.

**Comment by moigagoo** [comment]
> I will release this soon, but please try this out if you can.

Just tried it and it works!

You have to specify both IPv4 and IPv6 addresses though:
```
$ nimhttpd --address=127.0.0.1 --ipv6=0:0:0:0:0:0:0:1
```

**Comment by h3rald** [comment]
...yes, that works even now, with v1.5.1 I am planning to have those as default addresses, so when you run nimhttpd with no arguments it doesn't cause an error:

![image](https://user-images.githubusercontent.com/1169/220653308-1721904d-87cc-4e6b-8af0-4cc20543644e.png)

**Comment by moigagoo** [comment]
Oh, sorry, I thought you asked to check if this workaround worked with the current version.

Just checked on e3dcf87756c521180656c548d935a49f7c75623f, works fine.

**Comment by h3rald** [comment]
Alright, 1.5.1 is out containing the fix; closing this. Thank you everyone! 😊👍

**Comment by geotre** [comment]
Same error with 1.5.1 I'm afraid:

![image](https://user-images.githubusercontent.com/1889120/222790871-c79ed8d7-0b85-4e39-ae88-d687a806307f.png)
