### ISSUE TITLE
[question] Automatic update/refresh

### ISSUE THREAD

**Issue by heysokam** [h3rald/nimhttpd#18]
Is it possible to make nimhttpd update/refresh by itself when a file in the target folder is updated?

I'm finding myself opening my files in vscode just to be able to have the functionality that this extension provides:
https://marketplace.visualstudio.com/items?itemName=yandeu.five-server

I'm very new to webdev, so sorry if the question is too basic.
Is there a way around this in some way?

**Comment by h3rald** [comment]
Err I'd say that would be beyond the scope of this project. Such functionality is typically provided by dev servers for various languages, and it relies on WebSocket. I am probably not going to implement that (unless someone wants to submit a PR of course).
