### ISSUE TITLE
Not working in WIndows 0.20.0

### ISSUE THREAD

**Issue by kidandcat** [h3rald/nimhttpd#2]
In Windows 10, using new Nim 0.20.0 it listens port ok, but when first request comes:
```

NimHTTPd v1.0.6 started on port 1337.
Serving directory C:\Users\jairo\Desktop\front
C:\Users\jairo\scoop\apps\nim\current\lib\system\fatal.nim(48) sysFatal
C:\Users\jairo\scoop\apps\nim\current\lib\pure\asyncfutures.nim(353) read
C:\Users\jairo\scoop\apps\nim\current\lib\pure\asyncfutures.nim(353) read
C:\Users\jairo\scoop\apps\nim\current\lib\pure\asyncfutures.nim(400) :anonymous
Error: unhandled exception: value out of range: -1 [RangeError]
```

**Comment by h3rald** [comment]
Wow... nasty. Well, time to try the new version of non and recompile I guess... it's probably a stupid incompatibility introduced in the latest versions.

Will check it out when I get a chance, hopefully... next weekend :(

**Comment by h3rald** [comment]
Should be fixed now... I am not releasing yet because I need to setup a few cross-compilers first, but give it a go if you can!
