### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kidandcat** [h3rald/nimhttpd#5]
I'm getting this error when installing nimhttpd with nimble:

`Additional info: "Requested command not found: \'\\usr\\local\\bin\\x86_64-w64-mingw32-gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing -fno-ident  -IC:\\Users\\jairo\\Nim\\lib -IC:\\Users\\jairo\\AppData\\Local\\Temp\\nimble_5700\\githubcom_h3raldnimhttpd_#head\\src -o C:\\Users\\jairo\\nimcache\\nimhttpd_r\\stdlib_assertions.nim.c.o C:\\Users\\jairo\\nimcache\\nimhttpd_r\\stdlib_assertions.nim.c\'. OS error:" 2`

Nim version: devel

**Comment by kaushalmodi** [comment]
I am using the latest nim devel as of today (v1.3.5) and `nimble install nimhttpd` worked just fine.

**Comment by s0kil** [comment]
Can confirm package installs on the latest stable (1.2.0) and devel (1.3.3)

**Comment by h3rald** [comment]
Closing for now, please re-open if this issue comes up again...
