### ISSUE TITLE
`-p:0` (to select automatically an open port) should tell you which port was selected

### ISSUE THREAD

**Issue by timotheecour** [h3rald/nimhttpd#8]
see how i solved a similar problem here: https://github.com/nim-lang/Nim/pull/14327

**Comment by h3rald** [comment]
Yes, this would be nice! Feel free to open a pull request, especially since you already solved the same problem... 🙂 

Glad you are trying out nimhttpd 👍

**Comment by h3rald** [comment]
Implemented automatic port binding, thanks a lot @timotheecour!
