### ISSUE TITLE
Display address and port when running

### ISSUE THREAD

**Issue by avahe-kellenberger** [h3rald/nimhttpd#9]
It would be a nice QOL change to have the address and port printed to stdout, so we could simply click to open the link.

It's a small change, but would be nice.

**Comment by h3rald** [comment]
Hi! 

Not sure what you mean exactly... I think the latest version does it already:

![image](https://user-images.githubusercontent.com/1169/94547850-236e4300-0250-11eb-9d5e-b1a743dafe18.png)

**Comment by avahe-kellenberger** [comment]
My mistake, was on an outdated version. Thanks!
